resources:
  - oase-accept.yaml
  - oase-action.yaml
  - oase-agent.yaml
  - oase-apply.yaml
  - oase-ita-collaboration.yaml
  - oase-web.yaml
  - oase-zabbix-monitoring.yaml
  - oase-prometheus-monitoring.yaml
  - oase-grafana-monitoring.yaml
  - business-central.yaml
  - kie-server.yaml
  - mariadb.yaml
  - rabbitmq.yaml
